### ISSUE TITLE
Avatar/Profile Initials bleed outside of the space

### ISSUE THREAD

**Issue by pantone175c** [museumofthebible/wrs#27]
**Issue Description**
When viewing avatar/profile image, you see the user's initials bleed outside of the circle.

**Screenshot**
![screen shot 2017-01-17 at 10 44 39 am](https://cloud.githubusercontent.com/assets/631168/22030224/94383cc6-dca2-11e6-9570-b80eeff28f8b.png)

**Comment by eberharterm** [comment]
This can be closed, these are just dummy avatars and will be replaced with 2 character avatars

**Comment by pantone175c** [comment]
No fix.
